version: '3.8'

services:
  my-nodejs-project:
    build:
      context: ./my-nodejs-project
      dockerfile: /home/emmi/app/compose/my-nodejs-project/Dockerfile
    ports:
      - "3000:3000"

  my-dotnet-app:
    build:
      context: ./my-dotnet-app
      dockerfile: /home/emmi/app/compose/my-dotnet-app/Dockerfile
    ports:
      - "7075:8080"

  my-java-app:
    build:
      context: ./my-java-app
      dockerfile: /home/emmi/app/compose/my-java-app/Dockerfile
    ports:
      - "8077:8077"

